# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FojElfJH8-niSUyiLoKccK1R289lcjlI
"""

import matplotlib.pyplot as plt

students = {}

def add_student():
    name_m = input("Enter student's name: ")

    physics_m = float(input("Enter marks in physics: "))

    maths_m = float(input("Enter marks in maths: "))

    total = physics_m + maths_m

    students[name_m] = {
        "maths": maths_m,
        "physics": physics_m,
        "total": total
    }

def display_graph():

  student=input("Enter student name:")
  if student in students:
    physics = students[student]["physics"]
    maths =  students[student]["maths"]
    subjects = ["Maths","Physics"]
    marks = [maths, physics]
    plt.bar(subjects, marks)

    plt.xlabel("Student Name")
    plt.ylabel("Marks")
    plt.title("Student Marks")

    plt.show()

  else:
    print("Student not found.")

def compare_all_students():
  total_avg = sum(s["total"] for s in students.values()) / len(students)
  math_avg = sum(s["maths"] for s in students.values()) / len(students)
  physics_avg = sum(s["physics"] for s in students.values()) / len(students)

  student = input("Enter student name:")
  if student in students:
    physics = students[student]["physics"]
    maths =  students[student]["maths"]
    total = physics + maths

    categories = ["Maths","Physics","Total"]
    student_marks = [maths, physics, total]
    avg_marks = [math_avg, physics_avg, total_avg]

    plt.bar(categories, student_marks, label="Student",color="green")
    plt.bar(categories, avg_marks, label="Average",color="red")

    plt.xlabel("Student Name")
    plt.ylabel("Marks")
    plt.title("Student Marks compared to average")

    plt.show()

  else:
    print("Student not found.")

while True:
  print("--MENU--")
  print("\n1 Add Student")
  print("2 Display Student Graph")
  print("3 Compare With Average")
  print("4 Exit")

  choice = input("Enter choice: ")

  if choice == "1":
    add_student()
    print("Student added successfully")
  elif choice == "2":
    display_graph()
  elif choice == "3":
    compare_all_students()
  elif choice == "4":
    break
  else:
    print("Invalid choice")

